# Generated by Django 6.0.2 on 2026-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.IntegerField(default=0, verbose_name='Предполагаемые часы'),
        ),
    ]
